### ISSUE TITLE
--coveralls-id only seems to upload for the current run, not accumulated data

### ISSUE THREAD

**Issue by huonw** [SimonKagstrom/kcov#90] opened 2015-04-30 04:12 UTC
I'm using kcov's coveralls integration (which is great!), but I have multiple binaries I wish to test. (I'm writing a wrapper for kcov to make it easier to use with Rust's cargo on Travis CI, and libraries using cargo often have multiple test binaries.)

It seems that the information from multiple kcov runs is not collated into the data sent to coveralls, only the current run is uploaded (or, at least, only that run is displayed).

You can see an example here: https://coveralls.io/r/huonw/cogset . Particularly, https://coveralls.io/builds/2455018 (65%) vs. https://coveralls.io/builds/2455037 (83%). The first runs kcov my main test binary first, and then a smaller one (which exercises far fewer code-paths) and the latter is the same code, but with the binaries run in reverse order (commit, https://github.com/huonw/cogset/commit/d34607fec1691c48c917516c9a549302dff23401). In both cases, I'm only passing `--coveralls-id` to the second execution of kcov, but I see the same behaviour if I give it to both.

**Comment by SimonKagstrom** [comment] 2015-04-30 06:59
Hmm... Did you check manually if accumulation works for the HTML output?

I tried reproducing it, with a pretty trivial program, and for me it works. As a workaround, you could try merging the two runs manually, i.e.,

```
kcov /tmp/kcov-first <your-program-with-the-first-args>
kcov /tmp/kcov-second <your-program-with-the-second-args>
kcov --merge --coveralls-id=$TRAVIS_JOB_ID /tmp/kcov /tmp/kcov-first /tmp/kcov-second
```

which merges the output from multiple runs (of potentially different binaries).


Anyway, I'll see if I can find out what's wrong.

**Comment by SimonKagstrom** [comment] 2015-04-30 07:16
I took a closer look at your commits, and are there actually two binaries that get run: foo-* and cogset-*?

If so, accumulation won't work - that's only valid for multiple runs of a single binary. The merge workaround above should work though. Another thing I've been thinking of is to make it possible to upload the merged output to coveralls directly, i.e., something like

```
kcov /tmp/kcov-first <your-program-with-the-first-args>
kcov --coveralls-id-merged=$TRAVIS_JOB_ID /tmp/kcov-second <your-program-with-the-second-args>
```

or perhaps just assuming it's the merged data which should be uploaded if there are multiple binaries in the coverage report. That would solve this bug report.

**Comment by huonw** [comment] 2015-04-30 11:16
Unfortunately it seems `--merge --coveralls-id=...` doesn't do the upload (I may be doing something wrong): https://travis-ci.org/huonw/cogset/builds/60679955 is build 20, but that doesn't appear in https://coveralls.io/r/huonw/cogset .

**Comment by huonw** [comment] 2015-04-30 11:18
Oh, my apologies; I spoke too soon. `--merge` works well, thanks!

**Comment by SimonKagstrom** [comment] 2015-04-30 11:26
OK, good to hear!

I've noticed that there is sometimes a fairly lengthy delay in coveralls publishing results, so probably that's what happened here.

I'll keep the bug open for a while, because it's probably more straight-forward to just upload the merged data if someone runs kcov on several binaries.

**Comment by SimonKagstrom** [comment] 2015-04-30 11:59
Commit 27139ab basically makes the change described above, so after that you no longer need the --merge workaround.

The only difference is that the default behavior is to upload merged results if they exist, so you can run it as

```
kcov /tmp/kcov <first-program>
kcov --coveralls-id=$TRAVIS_JOB_ID /tmp/kcov <second-program>
```

and the results of both will be published.

**Closed by SimonKagstrom** 2015-04-30 11:59 UTC

**Comment by huonw** [comment] 2015-05-01 04:00
Great! (Thanks again for the nice tool.)
