### ISSUE TITLE
merge option: Merged output is different depending on order of input files

### ISSUE THREAD

**Issue by tdegude** [SimonKagstrom/kcov#118] opened 2015-10-30 16:59 UTC
Hello Simon,

I am currently testing kcov, especially merge option. And the following problem occurs :

I have the same script installed on 2 different machines. I launch kcov for this script on the first machine (I call it MG1) with some inputs in order to generate a first coverage report REPORT1. 

Then I do the same thing on the other machine (I call it MG2) but with different inputs in order to have a new coverage report REPORT2. So I have now 2 coverage reports for the same script but with different coverage status. 

I retrieve the REPORT2 from MG2 and I put it on MG1. I try to merge the 2 reports and I have this really strange result depending on the order of reports in the kcov command : 

Kcov  - -merge CoverageReport1 REPORT1 REPORT2 => Report is not OK : it seems only REPORT1 is taken into account

Kcov  - -merge CoverageReport2 REPORT2 REPORT1 => Report is OK, merge successfully done.

Unfortunatly, i cannot send you reports (zip files not supported by this site). If you want to see reports, send me a mail and i will give you the reports in the reply.

Thank you very much for any information you will give to me.
Best regards

Thierry Dégude.

**Comment by tdegude** [comment] 2015-10-30 17:07
I forgot one point. After investigation, the problem seems to be linked to metadata handling.
Regards
Thierry Dégude

**Comment by SimonKagstrom** [comment] 2015-10-30 19:34
Thanks for the report!

Yes, I suspect stored metadata as well. It's at least not trivial to reproduce. I've tried

```
kcov /tmp/kcov tests/main/python/main
kcov /tmp/kcov2 tests/main/python/main 1
```

to produce two coverage reports from the same script (but with different parameters). This is the Python test in the kcov tarball/git repo. Merging them with either

```
kcov --merge /tmp/merged /tmp/kcov /tmp/kcov2
kcov --merge /tmp/merged2 /tmp/kcov2 /tmp/kcov
```

produces the same output in both /tmp/merged and /tmp/merged2.

Therefore, I think it's related to your scripts in some way. You can email them to me if you have the opportunity, and I'll try to reproduce it from there.

**Comment by SimonKagstrom** [comment] 2015-11-03 11:15
I've tried this on the scripts you supplied, but swapping the inputs give the same results in my test.

Could you try the cloning the git repo and re-running the test? Should not make a difference, but I might have missed something.

**Comment by SimonKagstrom** [comment] 2015-11-03 11:16
See Issue #119 for the cannot-merge-merged output by the way.

**Comment by tdegude** [comment] 2015-11-05 09:53
Hi Simon,
Sorry for answering so late. I have a lot of others things to do this week. In fact we used v29 of kcov : we retrieved directly the “tar” archive on the GiHub.
And if I am not wrong, v29 is the last stable release. Do you think next versions could change something ?  

Moreover, we have checked the hardware : the 2 machines are identical so it seems no impact can be due to hardware.

Thierry

**Comment by SimonKagstrom** [comment] 2015-11-05 12:24
I don't think the git HEAD has any really significant changes with respect to this, but I cannot reproduce the problem even with your scripts, so it might be worth a try.

If I find some time later, I'll try with v29.

**Comment by SimonKagstrom** [comment] 2015-11-12 07:58
Fixed with 0998a89. The problem was that the merge parser looks at the file timestamp as well as the checksum to determine if it should be processed.

When a script (as here) is copied from one machine to another, it will get a new timestamp, and the coverage reports will therefore not match. The fix removes the check for timestamp and relies only on the file checksum to determine if a file should be included or not.

**Closed by SimonKagstrom** 2015-11-12 07:58 UTC

**Comment by tdegude** [comment] 2015-11-12 08:58
Hi Simon. Thank you very much for this solution. Does that mean you will create the v30 of kcov with this fix ?

**Comment by SimonKagstrom** [comment] 2015-11-12 10:23
Yes, I will, but probably it will be good if Issue #119  is part of v30 as well, so it will take a while until that.

For now you can run the latest git HEAD, it should work better than v29 (I think there are only bugfix commits there anyway).
