### ISSUE TITLE
kcov segfaults when the excutable is kcov

### ISSUE THREAD

**Issue by perillo** [SimonKagstrom/kcov#425] opened 2024-03-14 07:11 UTC
## kcov version

kcov 42 (but I can reproduce it with current master)

## Example

```console
> kcov cover kcov -h
kcov: Process exited with signal 11 (SIGSEGV) at 0x7ffff7759710
```

When using a development version of `kcov` as the executable, the coverage file for `src/configure.cc` reports a suspected line (in yellow):
```
1692 / 6 		setKey("kcov-binary-path", get_real_path(argv[0])); 861
```

After this line, the remaining code in the `parse` function is not covered.

**Comment by SimonKagstrom** [comment] 2024-03-14 15:10
I actually can't reproduce this either on Linux (albeit with a slightly older kcov) or on MacOs.

However, if there's a memory overwrite issue, I guess I might just miss it. Maybe something in get_real_path?

**Comment by perillo** [comment] 2024-03-15 16:17
Can you test with a build from master?

**Comment by SimonKagstrom** [comment] 2024-03-16 07:50
Sorry, wasn't clear: On MacOS, I tested with the latest master. Linux was slightly older.

Could it be that you have something in your path that affects it? E.g., for me it's

```
$ which kcov
/Users/ska/projects/build/kcov/src//kcov
```

**Comment by perillo** [comment] 2024-03-16 14:36
I used `kcov` from `/usr/bin/kcov`, installed from Arch Linux official package.

```console
> kcov /tmp/cover kcov
kcov: Process exited with signal 11 (SIGSEGV) at 0x7ffff7959710

________________________________________________________
Executed in    1.25 secs      fish           external
   usr time  668.68 millis  484.00 micros  668.20 millis
   sys time  518.00 millis  124.00 micros  517.88 millis
```

The address seems to be always the same.
For the timing, note that I'm using an old PC.

**Comment by SimonKagstrom** [comment] 2024-03-26 08:21
You could try to run with `--debug=31` to see if there's any particular address it doesn't like, and also with `--verify`.

Although in those cases, the covered process is  typically the one that crashes, not kcov itself.

**Comment by perillo** [comment] 2024-03-26 08:47
The problem is the error message; it always prints `kcov` instead of using `argv[0]` so it is not clear what process is crashing in this context.

Here is the output using `--verify` (from commit 5ae73ae):

```console
> build/bin/kcov --verify cover kcov
kcov: warning: kcov: WARNING: kcov has been built without libbfd-dev (or
kcov: binutils-dev), so the --verify option will not do anything.

kcov: Process exited with signal 11 (SIGSEGV) at 0x7ffff7759710
```

```console
> kcov --verify cover build/bin/kcov
kcov: 21 invalid breakpoints skipped in /usr/lib/libstdc++.so.6
Usage: kcov [OPTIONS] out-dir in-file [args...]

...
```

**Comment by SimonKagstrom** [comment] 2024-03-27 07:12
OK, so I  believe the issue is then with the compiled code (maybe in libstdc++, by the looks of it). If the DWARF information is incorrect, e.g., in the middle of an instruction, kcov will set a breakpoint that actually destroys the code that runs (since the encoding now means something else).

This is basically only an issue on x86, which has variable length instructions, and the `--verify` option disassembles the code and discards the faulty DWARF entries.


You can probably also get around this by e.g., `--include-pattern=kcov`, or `--skip-solibs`.

Anyway, I think I'll close this, since it's not really a bug in kcov, but in the toolchain. Also, covering kcov in general is only possible when using python or bash scripts, since ptrace is not recursive.

**Closed** 2024-03-28 07:11 UTC

**Comment by arzedlab** [comment] 2024-04-13 14:16
Good, day, the same error
```
kcov: Process exited with signal 4 (SIGILL) at 0x7ffff7b97057

kcov: Illegal instructions are sometimes caused by some GCC versions
kcov: miscompiling C++ headers. If the problem is persistent, try running
kcov: with --verify. For more information, see
kcov: http://github.com/SimonKagstrom/kcov/issues/18

kcov: WARNING: kcov has been built without libbfd-dev (or
kcov: binutils-dev), so the --verify option will not do anything.
```
binutils-dev installed built right, I even tried to change Cmake but error happening each time.

Linux: Linux 20.04.1 Ubuntu x86_64

**Comment by SimonKagstrom** [comment] 2024-04-16 05:14
@arzedlab, how did you build it? When you run cmake, it should printout if it finds libbfd so that it can disassemble the sources.

Anyway, I think that is really issue #18 , but there seems like the build didn't find libbfd which causes `--verify` to do nothing.
