### ISSUE TITLE
exclude-patterns: allow globbing to remove files from being covered

### ISSUE THREAD

**Issue by Flickdm** [SimonKagstrom/kcov#120] opened 2015-11-10 20:19 UTC
ie: test files like example_Test.cpp could be ignored so that they don't show up in the final result using something like "*_Test.cpp"

**Comment by SimonKagstrom** [comment] 2015-11-10 20:24
Could you give a more elaborate example? It sort of works like that already, so that if you give

```
kcov --exclude-pattern=_Test.cpp [...]
```

it will exclude everything which ends with _Test.cpp (or actually contains the string _Test.cpp).

**Comment by Flickdm** [comment] 2015-11-10 20:45
You see that's how I thought it worked but they keep showing up in the final result. Basically your tool (which is fantastic by the way) is being used to cover a large c++ code base and I'm trying to ignore any file that ends with _Test.cpp from the end result but I keep seeing them in the end result.

kcov --include-path=/home/build/Code/ --exclude-pattern=_Test.cpp --exclude-path=/home/build/Code/client/application/Unix/Debug/moc/,/home/build/Code/client/application/Unix/ui kcov_client /home/build/Code/client/application/Unix/Debug/client UnitTest

This is the command I am running but in the end I still see [...]/build/Code/common/ItemWithDBRecordIdUtils_Test.cpp or something similiar? Does the command need to be structured a specific way?

Thank you for getting back to me so quickly!

**Comment by SimonKagstrom** [comment] 2015-11-11 08:07
Thanks :-)

This is a bug then, I'll setup a test case to reproduce it. I think it's caused by the combination of --include-path= and --exclude-pattern=, which at least I probably haven't used. I often use things like

```
kcov --include-pattern=example --exclude-pattern=test/suite [...]
```

where the directory structure looks like this

```
  example/src           # The source code
  example/test/suite  # Unit test files
```

which behaves like you expected above (i.e., the unit test files and libraries etc are excluded, but the code-under-test is included).

**Comment by SimonKagstrom** [comment] 2015-11-11 11:11
I'm having trouble reproducing this. I'm using this directory structure under /tmp/test-kcov:

```
./a.sh
./a_Test.cpp      # Which is really just a shell script, but anyway!
./ui
./ui/svempo.sh
./moc
./moc/kalle.sh
```

and running kcov like this

```
cd /tmp/test-kcov
kcov --include-path=`pwd` --exclude-pattern=_Test.cpp --exclude-path=`pwd`/moc,`pwd`/ui /tmp/out ./a.sh
```

and the test behaves as it should, i.e., only a.sh is present in the report. What version of kcov are you using? Issue #81 describes a sort of similar issue, but that was fixed this spring.

**Comment by Flickdm** [comment] 2015-11-12 21:05
That was the issue! Sorry about that I'm picking up where someone else left off and I presumed that it was the latest version. Is there an easy way to determine the version? I noticed --version and -v were not an option?

**Comment by SimonKagstrom** [comment] 2015-11-13 04:06
OK, good to hear!

No, there's no way to determine the version, but I added Issue #121 to track that particular problem. Closing this report then!

**Closed by SimonKagstrom** 2015-11-13 04:06 UTC
