### ISSUE TITLE
stdout is not shown when using kcov on Ubuntu 20.04

### ISSUE THREAD

**Issue by alalazo** [SimonKagstrom/kcov#362] opened 2021-08-13 16:29 UTC
This is similar to #61. Given this simple script:
```console
$ cat run_it.sh
#!/bin/bash
echo "Hello"
```
I see the following:
```console
$ ls -l run_it.sh
-rwxrw-r-- 1 culpo culpo 26 Aug 13 15:56 run_it.sh
$ ./run_it.sh 
Hello
$ kcov $PWD/coverage run_it.sh
$
```
i.e. nothing gets printed to stdout when running under kcov. Using one of the workaround suggested in #61 changes the behavior:
```console
$ kcov --debug-force-bash-stderr $PWD/coverage run_it.sh
Hello
```
It's possibly done on purpose, but the `--debug-force-bash-stderr` is not shown from `kcov` help message. If it matters I am working on:
```console
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by SimonKagstrom** [comment] 2021-08-13 16:46
Hmm.. I don't see that issue here (on OSX though):

```
Simons-iMac:kcov ska$ kcov --bash-dont-parse-binary-dir /tmp/kcov /tmp/a.sh
Hello
```

Is this with the latest from git?

**Comment by alalazo** [comment] 2021-08-13 16:57
> Is this with the latest from git?

No, it's with kcov v38 packaged in the Ubuntu repository

**Comment by SimonKagstrom** [comment] 2021-08-13 17:09
I tried re-builing on v38 and it works for me there as well. Not sure if it can affect it, but my bash version is

```GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin17.7.0)```

**Comment by alalazo** [comment] 2021-08-13 17:14
Ok, I have a different bash version:
```console
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by alalazo** [comment] 2021-08-13 17:23
I think you can probably reproduce starting from a vanilla `ubuntu:20.04` docker image.

**Comment by alalazo** [comment] 2021-08-13 21:35
It should be reproducible if you run in this image:
```dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
    
RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install -y coreutils curl patchelf kcov emacs

RUN useradd -m bob
USER bob
WORKDIR /home/bob
```

**Comment by SimonKagstrom** [comment] 2021-11-06 18:15
I tried your docker image now, and I can reproduce it there. It seems to be caused by the xtrace FD support. A workaround is to use `--debug-force-bash-stderr`, which disables it altogether. Then I see the stdout output when using kcov as well.

**Comment by SimonKagstrom** [comment] 2021-11-07 18:32
Actually, this is only a problem with v38 (and presumably earlier). I've tested the latest git HEAD on ubuntu 20.04, and that works while v38 fails, so closing.

**Closed by SimonKagstrom** 2021-11-07 18:32 UTC
