### ISSUE TITLE
kcov doesn't build against binutils 2.29

### ISSUE THREAD

**Issue by Dridi** [SimonKagstrom/kcov#215] opened 2017-08-11 15:04 UTC
It could be since 2.28 but upgrading from Fedora 26 to 27 (not yet released) jumps from binutils 2.27 to 2.29 directly:

```
$ rpm --query --info binutils-devel
Name        : binutils-devel
Version     : 2.29
Release     : 5.fc27
[...]
Summary     : BFD and opcodes static and dynamic libraries and header files
Description :
This package contains BFD and opcodes static and dynamic libraries.

The dynamic libraries are in this package, rather than a seperate
base package because they are actually linker scripts that force
the use of the static libraries.  This is because the API of the
BFD library is too unstable to be used dynamically.

The static libraries are here because they are now needed by the
dynamic libraries.

Developers starting new projects are strongly encouraged to consider
using libelf instead of BFD.
```

When building `kcov` I see this:

```
-- Found LIBBFD: /usr/lib64/libbfd.so  
-- Could NOT find DYNINST (missing: DYNINST_LIBRARIES DYNINST_INCLUDE_DIR) 
-- Target architectures: x86_64
-- Checking for module 'zlib'
--   Found zlib, version 1.2.11
-- Checking for module 'libcurl'
--   Found libcurl, version 7.54.1
-- Found LibElf: /usr/lib64/libelf.so  
-- Found ElfUtils: /usr/lib64/libdw.so
```

If I put one and one together correctly, I'm assuming that `kcov` uses both `libelf` and `libbfd` and that ideally it should only use the former.

The compilation error:

```
/builddir/kcov/src/parsers/bfd-disassembler.cc: In constructor ‘BfdDisassembler::BfdDisassembler()’:
/builddir/kcov/src/parsers/bfd-disassembler.cc:72:20: error: ‘print_insn_i386’ was not declared in this scope
   m_disassembler = print_insn_i386;
                    ^~~~~~~~~~~~~~~
```

The change in binutils: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commitdiff;h=6394c606997f88acfc80de4dff33a4ae2de987b4

**Comment by SimonKagstrom** [comment] 2017-08-11 16:13
Thanks for the detailed report!

OK, I suppose I need to change that to default_print_insn for binutils >= 2.29. binutils is actually only used for ```--verify```, to check that the DWARF debug info is correct (well, and for the lldb-engine), so the dependency is proper.

binutils is optional though, but if it's installed it should at least work also for newer binutils.

**Comment by Dridi** [comment] 2017-08-11 16:59
I'll try to build it without binutils, however simply using `default_print_insn` didn't work for me. I was initially trying to make a patch but didn't manage.

```
diff --git a/src/parsers/bfd-disassembler.cc b/src/parsers/bfd-disassembler.cc
index 3e1324e..2e9e131 100644
--- a/src/parsers/bfd-disassembler.cc
+++ b/src/parsers/bfd-disassembler.cc
@@ -69,7 +69,7 @@ public:
        {
                memset(&m_info, 0, sizeof(m_info));
                init_disassemble_info(&m_info, (void *)this, BfdDisassembler::opcodesFprintFuncStatic);
-               m_disassembler = print_insn_i386;
+               m_disassembler = default_print_insn;
 
                m_info.arch = bfd_arch_i386;
 
```

I get this:

```
/builddir/kcov/src/parsers/bfd-disassembler.cc: In constructor ‘BfdDisassembler::BfdDisassembler()’:
/builddir/kcov/src/parsers/bfd-disassembler.cc:72:20: error: ‘default_print_insn’ was not declared in this scope
   m_disassembler = default_print_insn;
                    ^~~~~~~~~~~~~~~~~~
```

I couldn't find this symbol in installed headers so I'm assuming it is also internal and some public API should be used instead.

**Comment by Dridi** [comment] 2017-08-11 17:06
I can confirm that I can build `kcov` if I don't have `binutils-devel` installed. Other things break, but I should be able to send a patch for that.

**Comment by SimonKagstrom** [comment] 2017-08-11 18:42
Looking at this commit:

https://github.com/bminor/binutils-gdb/commit/6394c606997f88acfc80de4dff33a4ae2de987b4#diff-4726cb59e6e43719a280ee94e412a269

perhaps the problem is just that the contents of the header has been moved? I include dis-asm.h, but it seems like disassemble.h is now the proper way to go.

Could you try compiling with that change? If that works, I think the FindBinutils.cmake code should be changed to take this into consideration, and some ifdef stuff added to include the correct header for the binutils version.

**Comment by Dridi** [comment] 2017-08-11 18:53
I already tried, `disassemble.h` is a private header and is not installed, on purpose. Since I'm not familiar with the libraries involved, I opened an issue instead of a pull request.

**Comment by SimonKagstrom** [comment] 2017-08-12 06:43
OK, way ahead of me in other words :-)

Maybe a hack: does this work for you?

```
diff --git a/src/parsers/bfd-disassembler.cc b/src/parsers/bfd-disassembler.cc
index 3e1324e..d091901 100644
--- a/src/parsers/bfd-disassembler.cc
+++ b/src/parsers/bfd-disassembler.cc
@@ -62,6 +62,8 @@ const std::set<std::string> x86BranchInstructions =
                "ret",
 };
 
+extern int print_insn_i386              (bfd_vma, disassemble_info *);
+
 class BfdDisassembler : public IDisassembler
 {
 public:
```

**Comment by Dridi** [comment] 2017-08-12 16:29
It would work for me if it came with a "this is a temporary hack comment for binutils 2.29 support" comment. Regarding my personal needs, I'm doing fine without the optional binutils support, and I don't really know what feature I'm missing (if it's documented, feel free to RTFM me).

**Comment by Dridi** [comment] 2017-08-12 16:38
I also had a look around in `bcov` and `kcov` regarding licensing and came to the conclusion that `bcov` is GPLv2 for the lack of "or later" mention and therefore `kcov` should be too as derivative work. Current binutils is GPLv3+ and shouldn't be compatible with GPLv2 (only GPLv2+) so I'm not even sure `kcov` can link with `libbfd` while complying to its license. But hey, I'm not a lawyer and I could be completely misled.

By the way your COPYING file is outdated, you can grab a copy somewhere from the FSF's websites.

**Comment by SimonKagstrom** [comment] 2017-08-12 16:49
Well, I think it's pretty harmless to have until binutils decides to simply remove it.

Binutils is needed for ```--verify```, which is used to verify the DWARF debug information. Sometimes there are entries there which specify that (basically) file:line -> address mappings map into the middle of an instruction, and setting a breakpoint there will simply break the instruction and cause a crash. So with ```--verify```, kcov makes sure breakpoints are only set on instruction boundaries. I don't think this is ever a problem on non-x86 architectures, which doesn't have variable length instructions.

As for the licensing, I'll write a new issue about copying. As for the linking issue, I'd need to research that further. I'm not sure that the bcov heritage is that relevant anymore, I think it's basically only present in ptrace.cc these days, and quite limited there as well. But of course the basic idea behind kcov comes from bcov!

**Comment by SimonKagstrom** [comment] 2017-08-12 16:58
Are you able to check that ```--verify``` works with binutils 2.29 with the hack by the way?

Running kcov on itself typically requires ```--verify```.

**Comment by Dridi** [comment] 2017-08-12 18:06
Thanks, I will give `--verify` a try and let you know.

**Comment by Dridi** [comment] 2017-08-25 13:42
I'm afraid it it compiles fine but doesn't link...

**Comment by SimonKagstrom** [comment] 2017-08-25 17:00
OK, too bad. What is the linking error? print_insn_i386 isn't defined anymore?

**Comment by Dridi** [comment] 2017-08-25 17:05
Apparently the linker doesn't find the symbol, and it lives in a private include on purpose, so that's probably to be expected.

**Comment by SimonKagstrom** [comment] 2017-08-25 17:06
I'll download binutils-2.29 and try to figure out what to do about it.

**Comment by SimonKagstrom** [comment] 2017-08-25 17:16
Ouch. Forgot about C++ name mangling. The commit 68d8448 fixes that at least, although I haven't tested it yet. I think it should link though.

**Comment by Dridi** [comment] 2017-08-26 13:10
It works fine now, I'll update my package submission with binutils support and patch kcov 33 to include the missing bits.

**Comment by SimonKagstrom** [comment] 2017-08-26 13:59
Great! Closing with the workaround then!

**Closed by SimonKagstrom** 2017-08-26 13:59 UTC

**Comment by Dridi** [comment] 2017-08-26 14:07
For reference:

https://koji.fedoraproject.org/koji/taskinfo?taskID=21479803
https://koji.fedoraproject.org/koji/taskinfo?taskID=21479807
https://koji.fedoraproject.org/koji/taskinfo?taskID=21479811
https://koji.fedoraproject.org/koji/taskinfo?taskID=21479815

Builds fine on all current Fedora branches.

**Comment by SimonKagstrom** [comment] 2017-08-27 12:27
Great work, thanks for doing this!

kcov doesn't run any automatic tests for PPC though, so it's entirely possible that it has broken sometime. Same thing with ARM.
