### ISSUE TITLE
bash: Unexpected output when redirecting stderr>stdout

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [SimonKagstrom/kcov#61] opened 2015-02-19 19:04 UTC
Hi, again,

I have another simple test script:

````
#!/bin/bash
test -n "$FILE" && redirect="> ${FILE}"
eval echo stuff  2>&1 ${redirect:-}
````
When I ran it with kcov I expected to just see 'stuff'. What I got was this:
```
% kcov /tmp/kcov_out test.sh
kkcov@test.sh@3@echo stuff
stuff
```
When I set the FILE variable and run it again I get this:
```
% FILE=blather kcov /tmp/kcov_out test.sh
kkcov@test.sh@3@echo stuff
% cat blather
stuff
```
Mark E. Hamilton

**Comment by SimonKagstrom** [comment] 2015-02-19 20:35
This problem lies on a deeper level than kcov. kcov uses the PS4 environment variable to catch file/line information, like this:

```sh
ska@localhost:kcov$ PS4='kcov@${BASH_SOURCE}@${LINENO}@' bash -x tests/bash/redirect-stderr.sh 
kcov@tests/bash/redirect-stderr.sh@2@test -n ''
kcov@tests/bash/redirect-stderr.sh@3@eval echo stuff
kkcov@tests/bash/redirect-stderr.sh@3@echo stuff
stuff
```

and as you can see, the "kkcov@..." output ends up there as well. A workaround is probably pretty simple, but it would be nice to understand exactly why it happens. Probably something to do with the stderr -> stdout redirection?

**Comment by Mark-E-Hamilton** [comment] 2015-02-20 00:15
To make it more clear where things are going I added an extra echo to stderr to the test script:

````
% cat test2.sh
#!/bin/bash
test -n "$FILE" && redirect="> ${FILE}"
eval '{ echo error >&2 ; echo stuff ; }'  2>&1 ${redirect:-}

% bash -x test2.sh
+ test -n ''
+ eval '{ echo error >&2 ; echo stuff ; }'
++ echo error
error
++ echo stuff
stuff

% bash -x test2.sh 2>/dev/null
++ echo error
error
++ echo stuff
stuff

FILE=/dev/null bash -x test2.sh 2>/dev/null
++ echo error
error
++ echo stuff
````
Is looks like the redirect is affecting the xtrace output, too, sending it to stdout instead of stderr.

**Comment by SimonKagstrom** [comment] 2015-02-20 07:59
bash has the BASH_XTRACEFD environment variable, which allows the xtrace output to be sent somewhere else than stderr. This is probably the solution to go for here.

**Comment by Mark-E-Hamilton** [comment] 2015-02-20 16:18
Arrgh. My "UNIX in a Nutshell" doesn't mention BASH_XTRACEFD. Darn paper tech. ;) Sounds like a good approach, though. Thanks for looking at this.

**Comment by SimonKagstrom** [comment] 2015-02-20 18:38
:-)

It might simply be too old: This feature apparently arrived with Bash 4.1 in 2009. Anyway, I'm working with a fix which seems to work, but I believe it will be necessary to support bash < 4.1 as well.

**Comment by SimonKagstrom** [comment] 2015-02-20 18:53
The issue should be fixed with b11b3f1, but only if you run bash >= 4.1. I'll add a fix which falls back to using stderr for earlier versions soon, so I'll leave the bug report open for now.

**Comment by Mark-E-Hamilton** [comment] 2015-02-20 23:05
Hi,

I just pulled the new version, and now I get the PS4 line every time. Is 
it possible that some sort of debugging output got left in?

This is the ouput when testing my simple case statement test:

% kcov ./kcov_out ./test.sh a
kcov@./kcov_out/bash-helper.sh@4@set -x
kcov@./test.sh@2@case ${1} in
kcov@./test.sh@4@echo Got a
Got a


-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666

**Comment by SimonKagstrom** [comment] 2015-02-21 06:36
On Sat, Feb 21, 2015 at 12:05 AM, Mark E. Hamilton <notifications@github.com
> wrote:

> I just pulled the new version, and now I get the PS4 line every time. Is
> it possible that some sort of debugging output got left in?


What version of bash are you using?

Could you run a manual BASH_XTRACEFD test? E.g.,

```sh
exec 3>| trace.txt

BASH_XTRACEFD=3
set -x
echo does this work?
```

**Comment by SimonKagstrom** [comment] 2015-02-21 15:27
Commit f261c14 implements a check-for-bash-4.1-or-above.

I guess it would be possible to catch stdout as well and filter out the PS4 markers if they show up there for bashes which can't handle BASH_XTRACEFD. This won't be foolproof, but should probably be enough for your particular case.

**Comment by SimonKagstrom** [comment] 2015-02-21 18:49
Commit 6c1b539 filters stdout from kcov@-lines as well. Hopefully there aren't too many people around who depend on having to output that, but if there is I guess some more robust solution could be made.

Closing this issue now - at least I can't reproduce the problem either with the BASH_XTRACEFD solution or without it.

**Comment by Mark-E-Hamilton** [comment] 2015-02-23 16:36
Good morning,

We're using version 4.1.2 of BASH
```
% echo ${BASH_VERSION}
4.1.2(1)-release
```
The test you provided does seem to work (though I don't know where the printf statements are coming from. Something odd in our setup here.)
``
% export PS1='% '
% exec 3>| trace.txt
% BASH_XTRACEFD=3
% set -x
% echo does this work?
does this work?
ceerws3111a 999% cat trace.txt
++ printf '\033]0;%s@%s:%s\007' mhamilt ceerws3111a /sierra/dev/mhamilt/sntools_votd_5
+ echo does this 'work?'
++ printf '\033]0;%s@%s:%s\007' mhamilt ceerws3111a /sierra/dev/mhamilt/sntools_votd_5
+ cat trace.txt
````
I pulled again this morning, and my case statement test works differently now. Previously it output the `kcov@` lines but still echoed the message. Now I get no output from the echo statement.

````
% git describe
v25-27-ge5a3c51
% kcov /tmp/kcov_out test.sh a
kcov@/tmp/kcov_out/bash-helper.sh@4@set -x
kcov@test.sh@2@case ${1} in
kcov@test.sh@4@echo Got a

% cat test.sh
#!/bin/bash
case ${1} in
(a)  echo Got $1 ;;
(b)  echo Got $1 ;;
c) echo Got $1 ;;
*) echo Got $1 ;;
esac
````

**Comment by SimonKagstrom** [comment] 2015-02-23 18:38
Hmm... Something is strange here. For me I get the same output whichever way I run the test script you submitted above:

```sh
ska@localhost:target$ /tmp/test.sh a
Got a
ska@localhost:target$ kcov /tmp/kcov /tmp/test.sh a
Got a
ska@localhost:target$ kcov --debug-force-bash-stderr /tmp/kcov /tmp/test.sh a
Got a
```

The last invocation uses a debug flag to fake bash < 4.1 (to try the stdout filtering). Do you have something strange in you interactive shell environment? Could you try to run it with a clean environment, i.e.,

```sh
env -i /path/to/kcov /tmp/kcov_out /path/to/test.sh a
```
(which even clears PATH, thus the need for absolute paths).

**Comment by SimonKagstrom** [comment] 2015-02-23 18:44
Did you remember to build after you pulled?

**Comment by Mark-E-Hamilton** [comment] 2015-02-24 18:00
On 02/23/15 11:38, Simon Kagstrom wrote:
> Hmm... Something is strange here. For me I get the same output whichever
> way I run the test script you submitted above:
>
> ska@localhost:target$ /tmp/test.sh a
> Got a
> ska@localhost:target$ kcov /tmp/kcov /tmp/test.sh a
> Got a
> ska@localhost:target$ kcov --debug-force-bash-stderr /tmp/kcov /tmp/test.sh a
> Got a
>
> The last invocation uses a debug flag to fake bash < 4.1 (to try the
> stdout filtering). Do you have something strange in you interactive
> shell environment? Could you try to run it with a clean environment, i.e.,
>
> env -i /path/to/kcov /tmp/kcov_out /path/to/test.sh a
>
> (which even clears PATH, thus the need for absolute paths).

I'm always amazed when I learn things I never knew, considering how long 
I've been in this business. Thanks for that; I didn't know I could do that.

IAE, it's strange that I still get the same behavior I did yesterday. (I 
pulled this morning (v25-29-gafdfbf9), and used make -B.)

````
% ls -l /home/mhamilt/kcov/src/kcov
-rwxr-x--- 1 mhamilt wg-sierra-admin 5673720 Feb 24 10:44 
/home/mhamilt/kcov/src/kcov
% env -i /home/mhamilt/kcov/src/kcov /tmp/kcov_out ./test.sh a
kcov@/tmp/kcov_out/bash-helper.sh@4@set -x
kcov@test.sh@2@case ${1} in
kcov@test.sh@3@echo Got a
% cat test.sh
#!/bin/bash
case ${1} in
(a) echo Got $1 ;;
c) echo Got $1 ;;
*) echo Got $1 ;;
esac
````
I'm stumped as to why we would have different behavior. Though my test 
script was not executable when I made it so the behavior didn't change.

IAE, we're running a pretty vanilla RHEL6 machine with Bash 4.1.2:

````
% uname -a
Linux ceerws3111a 2.6.32-279.22.1.el6.x86_64 #1 SMP Sun Jan 13 09:21:40 
EST 2013 x86_64 x86_64 x86_64 GNU/Linux

% echo $BASH_VERSION
4.1.2(1)-release
````



-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666

**Comment by Mark-E-Hamilton** [comment] 2015-02-24 18:32
Okay, I've got to be doing something wrong. I know I've rebuilt the executable, and the commit I have is v25-29-gafdfbf9 on master, but when I run kcov with the --debug-force-bash-stderr you used above I get an invalid option error. Do I have the wrong version somehow?

**Comment by Mark-E-Hamilton** [comment] 2015-02-24 18:35
On 02/23/15 11:44, Simon Kagstrom wrote:
> Did you remember to build after you pulled?

No offence taken. At this point I don't know why I'm betting different 
behavior than you, so any question is valid.

-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666

**Comment by SimonKagstrom** [comment] 2015-02-24 18:50
You could try to add a printout in main.cc to just see that you're executing the correct binary.

Also, while it shouldn't make any difference, you could try building outside the source tree, i.e.,

```
mkdir bld
cd bld
cmake ..
make
```

**Comment by Mark-E-Hamilton** [comment] 2015-02-24 21:14
Looks like I am executing the binary that I built:
````
% kcov /tmp/mhamilt/kcov_out ./test.sh a
Hello, Mark
kcov@/tmp/mhamilt/kcov_out/bash-helper.sh@4@set -x
kcov@./test.sh@2@case ${1} in
kcov@./test.sh@3@echo Got a
````
The bld commands didn't work for me, however. It didn't create a Makefile in bld, so make failed.

**Comment by SimonKagstrom** [comment] 2015-02-25 07:57
Seems like we have a true mystery here!

The failing build with bld and the problem with --debug-force-bash-stderr seems strange. Feels like some cmake issue then, perhaps because an in-tree build is already present. Anyway, to reproduce my setup, could you try re-cloning the repo and building in a separate directory?

These exact steps work for me:

```
cd /some/place/
git clone https://github.com/SimonKagstrom/kcov.git
cd kcov
mkdir bld
cd bld
cmake ..
make -j4
src/kcov --debug-force-bash-stderr /tmp/kcov /tmp/test.sh a
```

It just outputs "Got a" and generates coverage info as expected. Reopening until this is sorted out.

**Comment by SimonKagstrom** [comment] 2015-02-25 08:07
I built bash 4.1 and ran that as well, and there are some interesting results from that:

```
$ src/kcov --bash-parser=/tmp/bash-4.1/bash  --debug-force-bash-stderr /tmp/kcov /tmp/test.sh a
Got a
$ src/kcov --bash-parser=/tmp/bash-4.1/bash /tmp/kcov /tmp/test.sh a
kcov@/tmp/kcov/bash-helper.sh@4@set -x
kcov@/tmp/test.sh@2@case ${1} in
kcov@/tmp/test.sh@3@echo Got a
```

so BASH_XTRACEFD does not seem to work with bash-4.1. With bash-4.2 it works. Commit a4c18d6 makes this change, so that bash 4.1 uses the stdout filtering workaround.

**Comment by Mark-E-Hamilton** [comment] 2015-02-25 17:32
Thanks for your responses. So, in order:

I whacked my clone and re-cloned it. You command sequence for building in a 'bld' subdirectory worked perfectly.  So, I made a new clone, built the makefile in source first, and then did the  'bld' directory tango. The makefile was not created in that sub-directory:
````
% cmake ${PWD} 
...
--
Build files have been written to: /ascldap/users/mhamilt/kcov2
% mkdir bld
% cd bld
% cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /ascldap/users/mhamilt/kcov2
% ls
%
````
The outdput indicates that it is writing to the top-level directory in both cases. I don't use cmake so I can't say whether this is normal behavior, but I believe you are correct that there is some odd behavior with regard to cmake when used this way.

I whacked them all and made a new clone, made sure I had the most recent commit, and built kdov in ths source tree (ie, the way I was doing so originally.)  It runs correctly both  with or without the --debug-force-bash-stderr option:
````
% git describe
v25-31-ga4c18d6
% src/kcov --debug-force-bash-stderr /tmp/kcov /tmp/test.sh a
Got a
% src/kcov /tmp/kcov /tmp/test.sh a
Got a
````
So I reset back to v25, built that, and saw the issues that existed then. I reset forward to b11b3f1,  built that, and got this error again:
````
% src/kcov  /tmp/kcov /tmp/test.sh a
kcov@/tmp/kcov/bash-helper.sh@4@set -x
kcov@/tmp/test.sh@2@case ${1} in
kcov@/tmp/test.sh@4@echo Got a
Got a
kcov: error: File /home/mhamilt/kcov2/test.sh exists, but can't be read???
````
I'm not sure why the last error occurred. The file does not exist in kcov2, and the command didn't reference it. IAE, I reset back up to a4c18d6 and it worked again (other than the kcov error):
````
% src/kcov  /tmp/kcov /tmp/test.sh a
Got a
kcov: error: File /home/mhamilt/kcov2/test.sh exists, but can't be read???
````
So, the PS4 issue seems to be resolved now. I don't know why it wasn't getting rebuilt correctly previously.

I'll submit another ticket later regarding the kcov error as soon as I figure out what's going on.

Thanks.

**Comment by SimonKagstrom** [comment] 2015-02-25 17:47
Good to hear that the PS4 issue is resolved! So closing this one now.

Perhaps the other problem is caused by the file move, but a kcov output directory that hasn't been removed (i.e., data has been collected for it)? In that case, removing /tmp/kcov should restore operation again.

I've seen the issue, but don't remember quite what causes it.

**Closed by SimonKagstrom** 2015-02-25 17:47 UTC
Labels: bash
