### ISSUE TITLE
Hangs on macOS

### ISSUE THREAD

**Issue by Jarred-Sumner** [SimonKagstrom/kcov#356] opened 2021-05-15 20:26 UTC
I compiled `kcov` from HEAD (and before that, tried the homebrew version), and when I try to run it, it hangs.

Also, I'm unable to use CTRL + C to kill the process. I have to `kill` the process manually. This happens whether or not the program crashes or returns a 0 exit code.

Note that this does not seem to happen when using built-in commands such as `/bin/ls` -- in that case, CTRL + C exits the process.

This is the particular command I ran:
```bash
kcov ./cover ./build/debug/macos-x86_64/esdev -- --help
```

`./build/debug/macos-x86_64/esdev` is a compiled binary written in [Zig](https://github.com/ziglang/zig) (which was compiled with LLVM 12).

There are files generated in `./cover`, so it doesn't appear to be a permissions issue.

Do you have any ideas of what else to try?

**Comment by SimonKagstrom** [comment] 2021-05-16 06:54
Strange.

One thing you could try is to limit the code to set breakpoints in, to see if it's a scalability issue, e.g.,

```kcov --include-pattern=file.extension ./cover ./build/debug/macos-x86_64/esdev -- --help```

You perhaps already saw #278, although that is for crashing processes. There was a similar issue with rust as well, #319, but I think that was caused by more external issues.

**Comment by judofyr** [comment] 2022-04-16 09:36
In case anyone else is struggling with this: The reason it was slow for me was because it was instrumenting the actual Zig standard library. I changed it to use `kcov --include-path . …` and then it became much faster.

**Comment by SimonKagstrom** [comment] 2022-04-16 17:24
Yes, unfortunately instrumentation on OSX is quite slow, so limiting the scope of the instrumented code with --include-pattern or --path often helps enormously. It's still very slow compared to Linux, but at least things improve that way.

Closing the issue, at least I hope it's not a generic hanging problem but more of a performance issue.

**Closed by SimonKagstrom** 2022-04-16 17:24 UTC

**Comment by Blacksmoke16** [comment] 2024-09-29 19:24
Not sure if its a kcov itself issue, or something with the homebrew package but I recently ran into this: https://github.com/athena-framework/athena/actions/runs/11094736512/job/30822531929. Was spinning for almost an hour, with no output from `--debug=31`. The program it was suck on is very small, and I was running with `--include-path="./src/components/$1/src"` so it only includes the source files.

I was able to switch to ubuntu and build from source and that seems to be working, but wanted to throw this here for posterity.

**Comment by SimonKagstrom** [comment] 2024-09-29 19:49
@Blacksmoke16 unfortunately, I think it's difficult to fix for the CI situation (at least with my limited MacOS understanding).

On MacOS, when running kcov the first time after a reboot (or login/logout), you get a graphical splash prompt that ask you if you want to allow kcov to debug your program. This comes from the system, so is nothing I've added. Thus, it works well when running locally and you can press OK (and accept with your password), but not via SSH or when the CI does it. I believe it will simply wait forever for that splash in that case.

It might be possible to sign it so that it's allowed to debug binaries without the prompt (like LLDB has), but I believe this must be done by higher powers and is something neither I nor Homebrew can do, as far as I know.


By the way, my last comment (about the slowness) is no longer true after a reimplementation of the MacOS kcov support. It now runs as fast as on Linux. This issue was for the original LLDB-based implementation, which was slow to the point of appearing to have hung.
