### ISSUE TITLE
kcov issue with backslash within string

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [SimonKagstrom/kcov#59] opened 2015-02-17 01:08 UTC
This might be related to #57; if so, feel free to drop this one, or merge them.

IAE, I have this test script:

````
#!/bin/bash
USAGE="usage: ${toolName} [--help] [--option1] \\
       [--option1|--option3] \\
       function_name [function_options] ...
"
````
It should produce no output, but when I run it with kcov I get this
````
% kcov /sierra/dev/mhamilt/kcov_out ./test.sh
       [--option1|--option3] \
       function_name [function_options] ...
'
````
If I add a `echo "$USAGE"` to the end of the script I get this output:

````
% kcov /sierra/dev/mhamilt/kcov_out ./test.sh
usage:  [--help] [--option1] \
       [--option1|--option3] \
       function_name [function_options] ...

       [--option1|--option3] \
       function_name [function_options] ...
'
       [--option1|--option3] \
       function_name [function_options] ...
'
````
This is with kcov-25 on a Linux RHEL6 machine using bash-4.1.2.

Thanks.

Mark E. Hamilton

**Comment by SimonKagstrom** [comment] 2015-02-17 07:23
Should be related at least, but I'll keep it open until it's known.

**Comment by SimonKagstrom** [comment] 2015-02-17 12:16
I did a quick test, and this and Issue #57 have the same root cause, so closing this.

**Closed by SimonKagstrom** 2015-02-17 12:16 UTC
Labels: bash
